### ISSUE TITLE
VS2022 extension broken on 17.3

### ISSUE THREAD

**Issue by josesimoes** [nanoframework/Home#1125]
### Tool

Visual Studio extension

### Description

When opening a nfproj in VS2022 17.3 the extension fails.

### How to reproduce

1. Open a nfproj 
2. VS output

LimitedFunctionality
System.ArgumentNullException: Value cannot be null.
Parameter name: commandLine
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectOptionsProcessor.SetCommandLine(String commandLine)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextProvider.<CreateProjectContextHandlingFaultAsync>d7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextProvider.<CreateProjectContextHandlingFaultAsync>d7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>cDisplayClass2_0.<Guard>gAction|0()
   at GuardMethodClass.GuardMethod(Func1 , Func2 , Func`2 )

**Comment by josesimoes** [comment]
Reported to VS Developer Community:
https://developercommunity.visualstudio.com/t/NET-nanoFramework-extension-broken-on-1/10116629 

## ⚠️  PLEASE UPVOTE the issue so it can be prioritized⚠️

**Comment by josesimoes** [comment]
cc @joperezr @Ellerbach
