### ISSUE TITLE
Deploying failed for TI CC3220SF

### ISSUE THREAD

**Issue by hololite** [nanoframework/Home#532]
Using VS2019.

Deploying the blinky app to the CC3220 failed. Below is the log 

2019-10-20 19:23:15Z [Check and start debug engine on nanoDevice.]
2019-10-20 19:23:15Z [Connect successful.]
2019-10-20 19:23:16Z [Erase deployment area successful.]
2019-10-20 19:23:16Z [Device status verified as being in initialized state. Requesting to resume execution.]
2019-10-20 19:23:16Z [Waiting for device to report initialization completed (1/5).]
2019-10-20 19:23:16Z [Device reported running nanoCLR. Requesting to reboot nanoCLR.]
2019-10-20 19:23:23Z [Device has completed initialization.]
2019-10-20 19:23:23Z [Computing deployment blob.]
2019-10-20 19:23:24Z [Deploying assemblies.]
2019-10-20 19:23:25Z [Incrementally deploying assemblies to the device]
2019-10-20 19:23:30Z [Error writing to device memory @ 0x0102F800 (2048 bytes). Error code: 0.]
2019-10-20 19:23:30Z [Error deploying assemblies to the device.]
2019-10-20 19:23:31Z [Deploying assemblies. Second attempt.]
2019-10-20 19:23:36Z [Deployment failed.]
2019-10-20 19:23:36Z [Exception occurred during deployment.
 Deploy failed. 

    at nanoFramework.Tools.VisualStudio.Extension.DeployProvider.<>cDisplayClass17_1.<<DeployAsync>b4>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at nanoFramework.Tools.VisualStudio.Extension.DeployProvider.<DeployAsync>d__17.MoveNext()]

**Comment by hololite** [comment]
Using nanoFramework v1.3.0.
